# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73299d4d5bcdebf47a49474754b8dfeedae1250fe517f21568394bc56a2150a2bb0532e43e109ea12c1ef686da4e5541e9984ba0ff0f18ea2e1914d40de2098b

test:
  secret_key_base: 001eb2e1fab43b35a215cf47375579621c5ff653ab10bbbf635cacc5dbaad597a12acbad22de9142bae34051ebc7cbae824294407ebe0befa736e481b8e59243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
